from efreq_rnum import EfreqRnum
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1500, 600)
        font = QtGui.QFont()
        font.setPointSize(14)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.docLabel = QtWidgets.QLabel(Dialog)
        self.docLabel.setObjectName("docLabel")
        self.verticalLayout.addWidget(self.docLabel)
        self.metricsTableWidget = QtWidgets.QTableWidget(Dialog)
        self.metricsTableWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.metricsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.metricsTableWidget.setWordWrap(True)
        self.metricsTableWidget.setObjectName("metricsTableWidget")
        self.metricsTableWidget.setColumnCount(8)
        self.metricsTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(7, item)
        self.metricsTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.metricsTableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.metricsTableWidget.horizontalHeader().setMinimumSectionSize(54)
        self.metricsTableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.metricsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.metricsTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.metricsTableWidget.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout.addWidget(self.metricsTableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.okPushButton = QtWidgets.QPushButton(Dialog)
        self.okPushButton.setMinimumSize(QtCore.QSize(150, 0))
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout.addWidget(self.okPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.docLabel.setText(_translate("Dialog", "TextLabel"))
        item = self.metricsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Понятие 1"))
        item = self.metricsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Понятие 2"))
        item = self.metricsTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Степ. близости (Sij)"))
        item = self.metricsTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Норм. степень близости (S\'ij)"))
        item = self.metricsTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Кол-во путей (Pij)"))
        item = self.metricsTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Мощнсоть понятия (Ub)"))
        item = self.metricsTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Вес дуги (Eij)"))
        item = self.metricsTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Bi*"))
        self.okPushButton.setText(_translate("Dialog", "OK"))


    def fill_metrics_table(self, efreq_rnum:EfreqRnum):
        self.metricsTableWidget.clearContents()
        self.metricsTableWidget.setRowCount(len(efreq_rnum.c_terms)**2)
        self.docLabel.setText(f'Параметры оценки \"{efreq_rnum.doc.filename}\"')
        row_count = 0
        for i in range(len(efreq_rnum.c_terms)):
            for j in range(i + 1, len(efreq_rnum.c_terms)):
                term_1 = QtWidgets.QTableWidgetItem(efreq_rnum.c_terms[i].name)
                term_2 = QtWidgets.QTableWidgetItem(efreq_rnum.c_terms[j].name)
                s_ij = QtWidgets.QTableWidgetItem(str(round(efreq_rnum.s[i,j], 3)))
                s_norm_ij = QtWidgets.QTableWidgetItem(str(round(efreq_rnum.s_norm[i,j], 3)))
                p_ij = QtWidgets.QTableWidgetItem(str(efreq_rnum.p[i,j]))
                mu_b = QtWidgets.QTableWidgetItem(str(round(efreq_rnum.mu_b, 3)))
                e_ij = QtWidgets.QTableWidgetItem(str(round(efreq_rnum.e[i,j], 3)))
                b_i = QtWidgets.QTableWidgetItem(str(round(efreq_rnum.b_i[i], 3)))

                self.metricsTableWidget.setItem(row_count, 0, term_1)
                self.metricsTableWidget.setItem(row_count, 1, term_2)
                self.metricsTableWidget.setItem(row_count, 2, s_ij)
                self.metricsTableWidget.setItem(row_count, 3, s_norm_ij)
                self.metricsTableWidget.setItem(row_count, 4, p_ij)
                self.metricsTableWidget.setItem(row_count, 5, mu_b)
                self.metricsTableWidget.setItem(row_count, 6, e_ij)
                self.metricsTableWidget.setItem(row_count, 7, b_i)
                row_count += 1
        self.metricsTableWidget.resizeColumnsToContents()

