# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/metrics_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1500, 600)
        font = QtGui.QFont()
        font.setPointSize(14)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.docLabel = QtWidgets.QLabel(Dialog)
        self.docLabel.setObjectName("docLabel")
        self.verticalLayout.addWidget(self.docLabel)
        self.metricsTableWidget = QtWidgets.QTableWidget(Dialog)
        self.metricsTableWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.metricsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.metricsTableWidget.setWordWrap(True)
        self.metricsTableWidget.setObjectName("metricsTableWidget")
        self.metricsTableWidget.setColumnCount(8)
        self.metricsTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.metricsTableWidget.setHorizontalHeaderItem(7, item)
        self.metricsTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.metricsTableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.metricsTableWidget.horizontalHeader().setMinimumSectionSize(54)
        self.metricsTableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.metricsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.metricsTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.metricsTableWidget.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout.addWidget(self.metricsTableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.okPushButton = QtWidgets.QPushButton(Dialog)
        self.okPushButton.setMinimumSize(QtCore.QSize(150, 0))
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout.addWidget(self.okPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.docLabel.setText(_translate("Dialog", "TextLabel"))
        item = self.metricsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Понятие 1"))
        item = self.metricsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Понятие 2"))
        item = self.metricsTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Степ. близости (Sij)"))
        item = self.metricsTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Норм. степень близости (S\'ij)"))
        item = self.metricsTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Кол-во путей (Pij)"))
        item = self.metricsTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Мощнсоть понятия (Ub)"))
        item = self.metricsTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Вес дуги (Eij)"))
        item = self.metricsTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Bi*"))
        self.okPushButton.setText(_translate("Dialog", "OK"))
